### ISSUE TITLE
add a way to configure ignore patterns

### ISSUE THREAD

**Issue by catdad** [catdad/electronmon#2]

**Comment by johnking** [comment]
I need it badly because my app will restart everytime when a data file changed.

**Comment by catdad** [comment]
This is now possible in v1.1.0.

For example, to ignore all files in the test directory, add this to your `package.json`:

```json
  "electronmon": {
    "patterns": ["!test/**"]
  },
```

**Comment by johnking** [comment]
it works! thanks
