### ISSUE TITLE
'getName function' is deprecated and will be removed

### ISSUE THREAD

**Issue by catdad** [catdad/electronmon#34]
I don't know what this error is or how to reproduce it... investigate later.

![image](https://user-images.githubusercontent.com/2205537/67637019-d26e0600-f8ac-11e9-8838-2a59ff072b12.png)

It happened on c647f202c58949b874d7108a4fe88ec2e0e04751, for line number info.

**Comment by erickzhao** [comment]
The bug seems related to the app you're running. The [`app.getName()` API](https://www.electronjs.org/docs/api/app#appgetname) and its counterpart `app.setName()` were deprecated some time ago.

The fix would just be to replace any instances of `app.getName()` with `app.name`.

**Comment by catdad** [comment]
Published in 1.0.1.
