### ISSUE TITLE
expose reload events via API for retaining SPA state

### ISSUE THREAD

**Issue by Awendel** [catdad/electronmon#63]
most sophisticated Electron apps are built in a SPA kind of manner, hence they expose various views just using Client logic.

Often when working on a given view & electronmon reloads the window, that view is lost & one has to manually navigate back to it.

It would be good if the module would expose an API for handling such things, in a manner like:

`electronmon.on("reload", ()=>{//custom reload logic})`

so one can then insert ones own navigation / routing logic to the last view one worked on.

**Comment by catdad** [comment]
This seems like a bad design. That is to say, putting code in your application that relies on electronmon seems like it would lead to bugs -- that is, your dev code now relies on something that shouldn't exist in prod (I seriously home electronmon doesn't exist in prod). Not to mention, this is not really necessary. You can use any arbitrary logic to persist and reconstruct state/views on any load (whether electronmon or a user closing and reopening an app). After all, most sophisticated apps resume right where you left off on restart 😉.

I don't want to encourage users to create a bad design, especially when there is such an easy and far better alternative.
