### ISSUE TITLE
Electronmon not working in Node v18?

### ISSUE THREAD

**Issue by mdodge-ecgrow** [catdad/electronmon#69]
I am using Electronmon to create a new Electron project in VSCode.  Everything was working just fine while I was using Node v16.17.0.  This is the output I see in the console when firing up the project in VSCode:
![image](https://user-images.githubusercontent.com/57459547/218861289-7cb9b724-a426-4fb1-b323-ae5604d01cfd.png)

Then I decided I wanted to upgrade to Node v18.13.0.  Then the app would not start at all, no GUI pops up.  And this is what I see in the console:
![image](https://user-images.githubusercontent.com/57459547/218861463-1016698b-9a6b-4592-97b8-25e50ed1af83.png)

So it seems to stop right before the line `[1] [electronmon] waiting for a change to restart it` which tells me that the issue is with Electronmon.  Anyone else seeing this?

**Comment by catdad** [comment]
Hmm, interesting. I updated CI to add node 18 and all the tests seem to pass, so that doesn't seem to be it: https://github.com/catdad/electronmon/actions/runs/4178971035

Did you change anything else in your application?

**Comment by mdodge-ecgrow** [comment]
That is the only thing I change between running the script `concurrently -k \"cross-env BROWSER=none npm start\" \"wait-on http://localhost:3006 && electronmon .\"`.  Must be something with the way its called in that script?

**Comment by catdad** [comment]
Yeah, there seems to be a lot going on in that script. Maybe try to run the individual commands to see if they all still work. All the electronmon tests are passing, so either I am missing something or the issue is somewhere else. Let me know if you get a reduced repro case for electronmon itself.

**Comment by Emily1799** [comment]
@mdodge-ecgrow Are you on Windows? There's an issue with wait-on and Node 18 where using "localhost" doesn't work. Try with 127.0.0.1

**Comment by mdodge-ecgrow** [comment]
> @mdodge-ecgrow Are you on Windows? There's an issue with wait-on and Node 18 where using "localhost" doesn't work. Try with 127.0.0.1

That was it!  Thank you!
I'll close this as it is not an issue with electronmon.
