### ISSUE TITLE
failed to quit app and electronmon process when window is closed

### ISSUE THREAD

**Issue by Yutiy** [catdad/electronmon#79]
### Summary

I tried to quit app when app window is closed, and expect to see electronmon process is terminated.
Below is my code

```
app.on('before-quit',  (event) => {
  event. preventDefault();
  // do Something
  app.exit();
});
```

It seems it only terminate the main process, while the electronmon process is still alive.
Showing below info when I close app window

`[electronmon] app exited with code 0, waiting for change to restart it`

**Comment by catdad** [comment]
That is expected behavior. See the [README](https://github.com/catdad/electronmon?tab=readme-ov-file#api-usage) (and honestly, also the message that tells you it is waiting for changes). If you want to exit the electronmon process, call the `destroy()` method.

**Comment by SRichner** [comment]
Hey @catdad, thanks for the awesome project!
I encountered the same "issue" in one of our projects and could not find any information in the README about this. It would be nice to mention it briefly (maybe similar to nodemon's readme).

**Comment by andrewschreiber** [comment]
FYI you can use  `process.kill(process.ppid, 'SIGTERM')` to kill both the electron and electronmon process from the main process.
